# Generated by Django 5.1.1 on 2024-09-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('FORD', 'Ford'), ('CHEVROLET', 'Chevrolet'), ('FIAT', 'Fiat'), ('VOLKSWAGEN', 'Volkswagen'), ('HYUNDAI', 'Hyundai'), ('HONDA', 'Honda'), ('TOYOTA', 'Toyota'), ('RENAULT', 'Renault'), ('NISSAN', 'Nissan'), ('JEEP', 'Jeep'), ('PEUGEOT', 'Peugeot'), ('CITROEN', 'Citroën'), ('MITSUBISHI', 'Mitsubishi'), ('BMW', 'BMW'), ('MERCEDES', 'Mercedes-Benz'), ('AUDI', 'Audi'), ('KIA', 'Kia'), ('LANDROVER', 'Land Rover'), ('VOLVO', 'Volvo'), ('CHERY', 'Chery')], max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(choices=[('PRETO', 'Preto'), ('BRANCO', 'Branco'), ('PRATA', 'Prata'), ('CINZA', 'Cinza'), ('VERMELHO', 'Vermelho'), ('AZUL', 'Azul'), ('VERDE', 'Verde')], max_length=255)),
                ('combustivel', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('ALCOOL', 'Álcool'), ('DIESEL', 'Diesel'), ('FLEX', 'Flex'), ('ELETRICO', 'Elétrico')], max_length=255)),
                ('quilometragem', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='carros/')),
            ],
        ),
    ]
