# Generated by Django 5.1.1 on 2024-10-19 01:22

import django.db.models.deletion
import minha_aplicacao.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_aplicacao', '0002_carro_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(validators=[minha_aplicacao.models.validar_ano]),
        ),
        migrations.AlterField(
            model_name='carro',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[minha_aplicacao.models.validar_preco]),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
