# Generated by Django 5.1.1 on 2024-12-02 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_aplicacao', '0004_rename_usuario_profile_user_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="O número de telefone deve estar no formato '+999999999'. Até 15 dígitos são permitidos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
